# Generated by Django 4.2.1 on 2023-06-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='follower',
        ),
    ]
