# Generated by Django 4.2.1 on 2023-06-15 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_remove_blogger_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='follower',
            field=models.ManyToManyField(blank=True, default='null', null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
